services:
  web:
    build: ./docker/app
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - jupyterlab
      - spark-master
      - spark-worker-1
      - spark-worker-2
    networks:
      - my-network

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.5.1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - BITNAMI_DEBUG=yes
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:29092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

  jupyterlab:
    container_name: jupyterlab
    build:
      context: ./docker/jupyterlab
      args:
        BASE_IMAGE: jupyter/base-notebook:latest
        spark_version: 3.4.1
        jupyterlab_version: 4.2.4
        sparksql_magic_version: 0.0.3
        kafka_python_version: 2.0.2
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    ports:
      - 8888:8888  # JupyterLab web interface
      - 4045:4040  # Spark UI inside JupyterLab container (changed from 4040 to 4045 on host)
    volumes:
      - shared-workspace:/home/jovyan/work
      - delta-tables:/home/jovyan/delta-tables
    depends_on:
      - spark-master
    networks:
      - my-network

  spark-master:
    container_name: spark-master
    build:
      context: ./docker/spark-master
      args:
        SPARK_BASE_IMAGE: bitnami/spark:3.4.1
    ports:
      - 8080:8080  # Spark Master Web UI
      - 7077:7077  # Spark Master Port
      - 4040:4040  # Spark Master UI Port
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_UI_PORT=4040  # Explicitly set UI port for Spark Master
    volumes:
      - shared-workspace:/home/jovyan/work
      - delta-tables:/home/jovyan/delta-tables
    networks:
      - my-network

  spark-worker-1:
    container_name: spark-worker-1
    build:
      context: ./docker/spark-worker
      args:
        SPARK_BASE_IMAGE: bitnami/spark:3.4.1
    ports:
      - 8081:8081  # Spark Worker 1 Web UI
      - 4041:4041  # Spark Worker 1 UI Port
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}       # Reference for worker cores
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}     # Reference for worker memory
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY} # Reference for executor memory
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}   # Reference for executor cores
      - SPARK_UI_PORT=4041  # Set UI port for Spark Worker 1
    volumes:
      - shared-workspace:/home/jovyan/work
      - delta-tables:/home/jovyan/delta-tables
    depends_on:
      - spark-master
    networks:
      - my-network

  spark-worker-2:
    container_name: spark-worker-2
    build:
      context: ./docker/spark-worker
      args:
        SPARK_BASE_IMAGE: bitnami/spark:3.4.1
    ports:
      - 8082:8082  # Spark Worker 2 Web UI
      - 4042:4042  # Spark Worker 2 UI Port
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}       # Reference for worker cores
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}     # Reference for worker memory
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY} # Reference for executor memory
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}   # Reference for executor cores
      - SPARK_UI_PORT=4042  # Set UI port for Spark Worker 2
    volumes:
      - shared-workspace:/home/jovyan/work
      - delta-tables:/home/jovyan/delta-tables
    depends_on:
      - spark-master
    networks:
      - my-network
  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   ports:
  #     # S3 API endpoint
  #     - "9000:9000"
  #     # Web console endpoint
  #     - "9001:9001"  
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data

volumes:
  shared-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/shared-workspace

  delta-tables:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/delta-tables

  # minio-data:
  #   driver: local

networks:
  my-network:
    driver: bridge