[supervisord]
nodaemon=true

[program:docker_registry]
command=/usr/bin/docker-registry serve /etc/docker/registry/config.yml
autostart=true
autorestart=true
stdout_logfile=/var/log/registry.log
stderr_logfile=/var/log/registry_err.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx_err.log
