server {
    listen 9003;  # Nginx will listen on port 9003

    location / {
        proxy_pass http://localhost:9000;  # Forward requests to MinIO server
        proxy_set_header Host $host;
        proxy_set_header X-Amz-Date $http_x_amz_date;
        proxy_set_header Authorization $http_authorization;
        proxy_hide_header X-Frame-Options;  # Remove the X-Frame-Options header for iframes
    }
    location /mybucket/ {
        proxy_pass http://localhost:9000/mybucket/;
        proxy_set_header Host $host;
        proxy_hide_header X-Frame-Options;
    }
    location /minio {
        proxy_pass http://localhost:9001;  # Forward requests to MinIO Console
        proxy_set_header Host $host;
        proxy_hide_header X-Frame-Options;  # Remove the X-Frame-Options header for iframes
    }
}
