FROM ghcr.io/dbt-labs/dbt-spark:1.5.latest

# Optional: Set the working directory
WORKDIR /usr/app/dbt

# Optional: Install additional Python dependencies if needed
# RUN pip install some_additional_package

# Copy your dbt project to the container
COPY ./dbt_project /usr/app/dbt
