ARG IMAGE=dbeaver/cloudbeaver:24.2.0
FROM ${IMAGE}

# # Set environment variables for initial setup
# ENV CB_ADMIN_NAME=admin \
#     CB_ADMIN_PASSWORD=admin123 \
#     CB_SERVER_NAME=MyCloudBeaver

# # Add custom configuration files
# COPY cloudbeaver.conf /opt/cloudbeaver/conf/cloudbeaver.conf

# # Add initial data sources (optional)
# COPY datasources.json /opt/cloudbeaver/workspace/.DataSources/datasources.json

# # Expose necessary ports
# EXPOSE 8080

# # Run CloudBeaver
# ENTRYPOINT ["/opt/cloudbeaver/run-server.sh"]