[kafka]
source_topic = your_topic
bootstrap_servers = 20.19.32.3:9094
output_topic = topic_processed

# 'topic' = 'shipments',
# 'properties.bootstrap.servers' = 'redpanda:29092',

# [influxdb]
# url = http://localhost:8086
# token = your-influxdb-token
# org = your-org-name
# bucket = your-bucket-name

